solution for 05 lection modal
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #11
Opened 2024-03-03 14:03 UTC by ArtemViktorovitch

2024-03-03 14:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-03 15:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-03 15:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 08:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 08:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 08:47 UTC, ArtemViktorovitch commented
Кажется разрешил конфликт

2024-03-05 08:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 08:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 09:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 14:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 14:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-06 15:20 UTC, GSemikozov requested changes

2024-03-06 15:20 UTC, GSemikozov commented on 05-lection3/02-modal/button/button.css
> +.button {
не надо файл стилей кнопки перетаскивать = дублировать сюда. Просто на хтмл странице задачи можно подключить main.css

2024-03-06 15:20 UTC, GSemikozov commented on 05-lection3/02-modal/button/button.css
> +.button {
который кстати и так подключен

2024-03-06 15:20 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +    <div id="modal" class="modal__wrapper">
modal__wrapper элемент содержит в себе modal? отец является сыном своего сына?) в общем modal__wrapper и есть modal, а modal - modal__inner / modal__window

2024-03-06 15:20 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    left: 0;
в этом случае модальное окно надо центрировать

2024-03-06 15:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-06 16:06 UTC, ArtemViktorovitch commented on 05-lection3/02-modal/button/button.css
> +.button {
Исправил

2024-03-06 16:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-06 16:21 UTC, ArtemViktorovitch commented on 05-lection3/02-modal/modal.css
> +    left: 0;
Кажется сделал

2024-03-06 16:21 UTC, ArtemViktorovitch commented on 05-lection3/02-modal/index.html
> +    <div id="modal" class="modal__wrapper">
Переименовал

2024-03-06 16:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-06 17:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-06 18:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-07 19:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-08 10:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-11 14:15 UTC, GSemikozov approved these changes

2024-03-11 14:15 UTC, merged