solution for 06 lection background
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #13
Opened 2024-03-12 15:23 UTC by ArtemViktorovitch

2024-03-12 15:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 21:37 UTC, GSemikozov requested changes

2024-03-12 21:37 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 400px) {
лишний медиа запрос, эта картинка ставится по умолчанию)

2024-03-12 21:37 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width:400px) and (max-width: 768px) {
range не надо, просто min-width

2024-03-12 21:37 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width:400px) and (max-width: 768px) {
768

2024-03-12 21:37 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width:768px) and (max-width: 1024px) {
1024

2024-03-12 21:37 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width:1024px) and (max-width: 2560px) {
2560

2024-03-13 08:51 UTC, ArtemViktorovitch commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 400px) {
Понял. Поправил.

2024-03-13 08:51 UTC, ArtemViktorovitch commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width:400px) and (max-width: 768px) {
Исправил.

2024-03-13 08:51 UTC, ArtemViktorovitch commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width:768px) and (max-width: 1024px) {
Исправил

2024-03-13 08:51 UTC, ArtemViktorovitch commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width:1024px) and (max-width: 2560px) {
Исправил.

2024-03-13 08:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-13 09:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 10:39 UTC, GSemikozov approved these changes

2024-03-14 10:40 UTC, merged