solution for 07 lection checkbox
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #18
Opened 2024-03-16 13:56 UTC by ArtemViktorovitch

2024-03-16 13:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-18 15:20 UTC, GSemikozov requested changes

2024-03-18 15:20 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:disabled ~ .checkbox__state
чтобы по сути 3 раза не писать одно и то же, достаточно раз на уровне `.checkbox__input:disabled ~ .checkbox__state` указать

2024-03-18 15:20 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    width: 70%;
а точно надо так уменьшать?)

2024-03-20 13:42 UTC, ArtemViktorovitch commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:disabled ~ .checkbox__state
Понял. Исправил.

2024-03-20 13:43 UTC, ArtemViktorovitch commented on 07-lection5/01-checkbox/checkbox.css
> +    width: 70%;
Как будто бы так лучше выглядело, вернул оригинальные размеры.

2024-03-24 14:54 UTC, GSemikozov approved these changes

2024-03-24 14:54 UTC, merged