solution for 07 lection input
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #21
Opened 2024-03-16 17:54 UTC by ArtemViktorovitch

2024-03-16 17:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-17 15:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 15:25 UTC, GSemikozov requested changes

2024-03-18 15:25 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <label class="form-input">
а вот в случае с инпутом как раз и не надо все заворачивать в лейбл)

2024-03-18 15:25 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <div class="form-input__label" for="input">
вот ЭТО - лейбл :)

2024-03-18 15:25 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    left: 310px;
не нужно, можно просто справа right: 16px

2024-03-18 15:25 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +::placeholder {
если глобальная штука - то в normalize

2024-03-20 12:53 UTC, ArtemViktorovitch commented on 07-lection5/04-input/index.html
> +        <label class="form-input">
Ясно, поменял на див.

2024-03-20 12:54 UTC, ArtemViktorovitch commented on 07-lection5/04-input/index.html
> +            <div class="form-input__label" for="input">
Завернул в лэйбл.

2024-03-20 13:12 UTC, ArtemViktorovitch commented on 07-lection5/04-input/input.css
> +    left: 310px;
ЗДесь не совсем понял: размеры изображения я должен контролировать из цсс: т.к. размеры из разметки свг убрал. По размещению тоже не допонял: изображение равняю относительно общей с инпутом обертки, там ширина на весь вьюпорт.

2024-03-20 13:12 UTC, ArtemViktorovitch commented on 07-lection5/04-input/input.css
> +::placeholder {
Ясно. Убрал  в normalize.

2024-03-20 13:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-20 13:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-20 14:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-20 15:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-24 14:58 UTC, GSemikozov requested changes

2024-03-24 14:58 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <div class="form-input__label">
вот ЭТО - label

2024-03-24 14:58 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label class="form-input__state" for="input">
а не вот это)

2024-03-24 14:58 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    left: 310px;
почему left работать не будет: если ширину не фиксировать (что было бы правильно), то при разной ширине иконка была бы в разных местах. Именно об этом был коммент про right

2024-03-26 08:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-26 08:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-26 09:27 UTC, ArtemViktorovitch commented on 07-lection5/04-input/index.html
> +            <div class="form-input__label">
Кажется понял, поправил.

2024-03-26 09:28 UTC, ArtemViktorovitch commented on 07-lection5/04-input/input.css
> +    left: 310px;
Хорошо, завернул во флекс, сделал резиновым. убрал left.

2024-03-26 09:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-01 18:02 UTC, GSemikozov approved these changes

2024-04-01 18:02 UTC, merged