solution for 10 lection theme
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #24
Opened 2024-03-26 11:48 UTC by ArtemViktorovitch

2024-03-26 11:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-01 18:03 UTC, GSemikozov requested changes

2024-04-01 18:03 UTC, GSemikozov commented on 10-lection8/01-theme-changer/theme-changer.css
> +.toggle {
мы же уже реализовывали отдельно тогл)

2024-04-02 07:43 UTC, ArtemViktorovitch commented on 10-lection8/01-theme-changer/theme-changer.css
> +.toggle {
Это и есть реализованный ранее тоггл, просто в этой ветке он отсутствует, так что подключить стили не получилось - просто скопипастил решение.

2024-04-03 19:51 UTC, GSemikozov commented on 10-lection8/01-theme-changer/theme-changer.css
> +.toggle {
в таких случаях надо либо подождать, либо делать чекаут от ветки с тогл и использовать его код, но не копипастить в другое место)
сейчас тогл принят, так что время подправить этот ПР.

2024-04-06 15:23 UTC, ArtemViktorovitch commented on 10-lection8/01-theme-changer/theme-changer.css
> +.toggle {
Понял. Выполнил слияние и подтянул стили из готового решения.

2024-04-08 14:30 UTC, GSemikozov requested changes

2024-04-08 14:30 UTC, GSemikozov commented on 10-lection8/01-theme-changer/theme-changer.css
> +html {
это же глобальные стили, они должны лежать там где предложено в задаче (в style страницы например)

2024-04-09 14:43 UTC, ArtemViktorovitch commented on 10-lection8/01-theme-changer/theme-changer.css
> +html {
Понял. Т.е. глобальные стили не должны быть в стилях блоков и т.п. Перенес в стили страницы.

2024-04-10 08:17 UTC, GSemikozov approved these changes

2024-04-10 08:18 UTC, merged