added checked status animation
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #25
Opened 2024-03-26 13:32 UTC by ArtemViktorovitch

2024-03-26 13:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-01 18:04 UTC, GSemikozov requested changes

2024-04-01 18:04 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +        border-radius: 25%;
а начальное значение какое?

2024-04-02 07:48 UTC, ArtemViktorovitch commented on 07-lection5/01-checkbox/checkbox.css
> +        border-radius: 25%;
Не совсем понял, начальное значение  0 пикселей, с него бордер расширяется до 25 пикселей.

2024-04-03 19:53 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +        border-radius: 25%;
смысл в том, что в keyframes мы должны явно определять то ОТ чего и то К ЧЕМУ делаем плавный переход. В данном коде на 100% появляется бордер, хотя на 0 у нас никакое значение не определено

2024-04-06 15:40 UTC, ArtemViktorovitch commented on 07-lection5/01-checkbox/checkbox.css
> +        border-radius: 25%;
Я думал, что 0 является валидным начальным значением, исправил на 1 пиксель.

2024-04-08 14:32 UTC, GSemikozov requested changes

2024-04-08 14:32 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +        border-radius: 25%;
не вижу где исправлено на 1px. Да и не надо) просто надо добавить в 
```
0% {
        border: solid 1px rgba(55, 79, 199, 1);
    }
```
строку про изначальное состояние радиуса:
```
0% {
        border: solid 1px rgba(55, 79, 199, 1);
border-radius: 0;
    }
```
это если в стилях самого элемента не определено.

2024-04-09 14:45 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-09 14:53 UTC, ArtemViktorovitch commented on 07-lection5/01-checkbox/checkbox.css
> +        border-radius: 25%;
Так а вот строчка: "border: solid 1px rgba(55, 79, 199, 1);", разве не оно в плане исправления? border-radius: 0; - добавил.

2024-04-09 14:55 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-10 08:18 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +        border-radius: 25%;
нет, речь про радиус - его нет в первой точки прохождения анимации

2024-04-10 08:18 UTC, GSemikozov approved these changes

2024-04-10 08:18 UTC, merged