03 lection 02-accordion
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #5
Opened 2024-02-24 12:43 UTC by ArtemViktorovitch

2024-02-24 12:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-24 14:15 UTC, GSemikozov requested changes

2024-02-24 14:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 250px;
лишнее ограничение

2024-02-24 14:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border-radius: 10px;
кажется 8

2024-02-24 14:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 10px 20px 10px 20px;
паддинги не по макету

2024-02-24 14:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 0;
лишнее

2024-02-24 14:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    box-shadow: 5px 5px 15px 5px rgba(0,0,0,0.8);
по макету не было

2024-02-24 14:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 10px 20px 10px 20px;
<img width="220" alt="Screenshot 2024-02-24 at 16 13 19" src="https://github.com/js-tasks-ru/htmlcss-20240216_del-ry4me/assets/6191270/c24e0bce-d130-4f7e-a7c9-bb4b426c5c43">

2024-02-24 14:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 1px solid var(--grey4);
бордеры на уровне accordion__item задаются

2024-02-24 14:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 8px;
не по макету

2024-02-24 14:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-24 15:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-25 12:12 UTC, GSemikozov requested changes

2024-02-25 12:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
когда .accordion__item[open] - `padding-bottom: 32px`

2024-02-25 12:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content {
еще по идее должен быть отступ от тайтла

2024-02-25 12:46 UTC, ArtemViktorovitch commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
Добавил стиль.

2024-02-25 13:03 UTC, ArtemViktorovitch commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content {
Добавил маржин 46рх для скрытого текста, но кажется это перебор.

2024-03-04 21:20 UTC, GSemikozov requested changes
осталось исправить конфликты

2024-03-05 08:13 UTC, ArtemViktorovitch commented
Сделал пуш апстрим мастер

2024-03-05 21:11 UTC, GSemikozov approved these changes

2024-03-05 21:11 UTC, merged