Layout for project page (main blocks)
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #6
Opened 2024-02-24 15:19 UTC by ArtemViktorovitch

2024-02-24 15:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-25 06:16 UTC, GSemikozov requested changes

2024-02-25 06:16 UTC, GSemikozov commented on components/footer/footer.css
> +    position:fixed;
на текущий момент все что касается позиционирования (position) - не надо использовать, мы эту тему еще не изучали и здесь это точно лишнее)

2024-02-25 08:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-25 08:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-25 12:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-25 12:34 UTC, ArtemViktorovitch commented on components/footer/footer.css
> +    position:fixed;
Убрал стиль.

2024-02-25 12:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-25 13:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-27 12:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-04 21:21 UTC, GSemikozov requested changes
осталось поправить конфликты

2024-03-05 09:05 UTC, ArtemViktorovitch commented
Кажется поправил

2024-03-06 15:10 UTC, GSemikozov requested changes

2024-03-06 15:10 UTC, GSemikozov commented on assets/css/main.css
> +    --white-1: #F9FAFC;
это grey :)

2024-03-06 15:10 UTC, GSemikozov commented on components/component/component.css
> +    margin-right: 165px;
марджины на уровне блока не задаем, решаем этот вопрос через родителя

2024-03-06 15:10 UTC, GSemikozov commented on components/component/component.css
> +    margin-top: 36px;
см ниже

2024-03-06 15:10 UTC, GSemikozov commented on components/card/card.css
> +    flex-basis: 350px;
лишнее

2024-03-06 15:10 UTC, GSemikozov commented on components/container/container.css
> +    /*max-width: 1110px;*/
вот это как раз правильно

2024-03-06 15:10 UTC, GSemikozov commented on components/container/container.css
> +    justify-content: space-between;
6-8 - это как раз не суть контейнера, контейнер просто центрирует контент

2024-03-06 15:10 UTC, GSemikozov commented on components/container/container.css
> +.container_grid-style {
и это тоже не про контейнер. Это либо блок какой-то, либо элемент какого-то блока

2024-03-06 15:10 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +    margin-left: 165px;
везде где добавляем такой марджин - это не надо, у нас есть контейнер, который центрирует контент

2024-03-07 17:37 UTC, ArtemViktorovitch commented on assets/css/main.css
> +    --white-1: #F9FAFC;
Хорошо, исправил.

2024-03-07 17:39 UTC, ArtemViktorovitch commented on components/container/container.css
> +    /*max-width: 1110px;*/
Понял, применил.

2024-03-07 18:35 UTC, ArtemViktorovitch commented on components/container/container.css
> +    justify-content: space-between;
Переслушал третью лекцию, понял. Создал новый элемент, занимающийся выравниванием по сетке.

2024-03-07 18:35 UTC, ArtemViktorovitch commented on components/container/container.css
> +.container_grid-style {
Кажется понял.

2024-03-07 18:36 UTC, ArtemViktorovitch commented on components/component/component.css
> +    margin-right: 165px;
Убрал.

2024-03-07 19:45 UTC, ArtemViktorovitch commented on components/component/component.css
> +    margin-top: 36px;
А как тогда отобразить элемент? И что делать с высотой? Контейнер как родитель не позволяет растягивать грид до футера.

2024-03-07 19:46 UTC, ArtemViktorovitch commented on components/card/card.css
> +    flex-basis: 350px;
Тут не совсем понял: это же отображение карточки.

2024-03-07 19:47 UTC, ArtemViktorovitch commented on components/sidebar/sidebar.css
> +    margin-left: 165px;
Применил контейнер.

2024-03-08 10:02 UTC, ArtemViktorovitch commented on components/container/container.css
> +    justify-content: space-between;
Убрал блоки выравнивающие по сетке, т.к. они еще больше нарушают конвенции БЭМ

2024-03-11 13:05 UTC, GSemikozov requested changes

2024-03-11 13:05 UTC, GSemikozov commented on components/card/card.css
> +    flex-basis: 350px;
ранее выше была указана фиксированная ширина. Сейчас - ок, можно оставить flex-basis

2024-03-11 13:05 UTC, GSemikozov commented on components/card/card.css
> +        flex: 1 1 45%;
это лишнее, на мобилке (ди а на десктопе) достаточно разруливать через родителя - способ выравнивания + gap

2024-03-11 13:05 UTC, GSemikozov commented on components/footer/footer.css
> +    padding: 72px 400px 136px 400px;
используем контейнер вместо таких паддингов по краям

2024-03-11 13:05 UTC, GSemikozov commented on components/footer/footer.css
> +    padding-bottom: 56px;
паддинги должны быть одинаковыми, здесь даже модификатор говорит сам за себя (что меняем только фон)

2024-03-11 13:05 UTC, GSemikozov commented on components/footer/footer.css
> +        padding: 100px 0 0 0;
не надо)

2024-03-11 13:05 UTC, GSemikozov commented on components/header/header.css
> +    padding:66px 0 77px 160px;
используем контейнер, паддинг слева не нужен

2024-03-11 13:05 UTC, GSemikozov commented on components/preview/preview.css
> +.preview .container {
нельзя из одного блока переопределять другой. Когда расположение одного зависит от другого - используем микс

2024-03-12 17:47 UTC, ArtemViktorovitch commented on components/header/header.css
> +    padding:66px 0 77px 160px;
Убрал.

2024-03-12 18:07 UTC, ArtemViktorovitch commented on components/preview/preview.css
> +.preview .container {
Вроде смиксовал.

2024-03-12 18:08 UTC, ArtemViktorovitch commented on components/footer/footer.css
> +        padding: 100px 0 0 0;
Убрал

2024-03-12 18:09 UTC, ArtemViktorovitch commented on components/footer/footer.css
> +    padding-bottom: 56px;
Убрал паддинг.

2024-03-12 18:15 UTC, ArtemViktorovitch commented on components/footer/footer.css
> +    padding: 72px 400px 136px 400px;
Применил модифицированный контейнер

2024-03-12 18:25 UTC, ArtemViktorovitch commented on components/card/card.css
> +        flex: 1 1 45%;
Убрал, оставил организацию флекс контейнера у родителя.

2024-03-14 10:46 UTC, GSemikozov requested changes

2024-03-14 10:46 UTC, GSemikozov commented on components/card/card.css
> +    flex-basis: 350px;
хотя не ок) мы же не знаем заранее что родитель всегда будет флексом, верно? так что это значение в принципе можно удалить

2024-03-14 10:46 UTC, GSemikozov commented on components/card/card.css
> +        flex-basis: 164px;
и тут

2024-03-14 10:46 UTC, GSemikozov commented on components/container/container.css
> +.container_640-px {
.container_small

2024-03-14 10:46 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__title_for-template {
можем использовать не только на странице компонента, это просто общий отдельный элемент, например .footer__disclaimer / .footer__text

2024-03-14 10:46 UTC, GSemikozov commented on components/preview/preview.css
> +    gap: 30px 30px;
gap: 30px

2024-03-14 10:47 UTC, GSemikozov commented on components/component/component.css
> +    margin-top: 36px;
родитель позволяем задавать gap, а насчет высоты - хочется растянуть на весь экран по высоте? в целом, в этом нет необходимости,

2024-03-17 13:08 UTC, ArtemViktorovitch commented on components/card/card.css
> +        flex-basis: 164px;
Удалил.

2024-03-17 13:11 UTC, ArtemViktorovitch commented on components/container/container.css
> +.container_640-px {
Переделал.

2024-03-17 13:15 UTC, ArtemViktorovitch commented on components/footer/footer.css
> +.footer__title_for-template {
Выделил в элемент .footer__text

2024-03-17 13:16 UTC, ArtemViktorovitch commented on components/preview/preview.css
> +    gap: 30px 30px;
Исправил.

2024-03-24 14:53 UTC, GSemikozov approved these changes

2024-03-24 14:53 UTC, merged