solution for 04 lection histogram
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #7
Opened 2024-02-27 14:26 UTC by ArtemViktorovitch

2024-02-27 14:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-04 21:28 UTC, GSemikozov requested changes

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
ширину и высоту убираем

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-bottom: 24px;
`padding: 28px 26px 32px`

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border-radius: 12px;
8

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 50%;
в общем-то лишнее

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    min-width: 9px;
а вот здесь flex-basis

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: stretch;
лишнее

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <p class="histogram__button">View all</p>
`<a>`

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 50%;
лучше сгруппировать text + number в колонку (или text + button в row)

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 24px;
лишнее

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 16px;
точно надо?

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 26px;
лишнее

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 19px;
лишнее

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 24px;
лишнее

2024-03-04 21:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 50%;
лишнее

2024-03-05 12:18 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
Убрал

2024-03-05 12:19 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    padding-bottom: 24px;
Указал, изменил

2024-03-05 12:19 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    border-radius: 12px;
Поменял

2024-03-05 12:44 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    min-width: 9px;
Боюсь, не совсем понял, что от меня требуется.

2024-03-05 12:51 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/index.html
> +            <p class="histogram__button">View all</p>
Правильно я понял, что  только у View all?

2024-03-05 13:02 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    align-items: stretch;
Убрал

2024-03-05 13:56 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 50%;
Вроде сделал

2024-03-05 13:57 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 24px;
Убрал

2024-03-05 13:59 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 26px;
Убрал

2024-03-05 14:05 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 19px;
Убрал

2024-03-05 14:06 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 24px;
Убрал

2024-03-05 14:06 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 50%;
Убрал

2024-03-06 15:11 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    min-width: 9px;
flex-basis: 9px

2024-03-06 15:13 UTC, GSemikozov requested changes

2024-03-06 15:13 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <a class="histogram__button">View all</a>
не button получается, а link ))

2024-03-06 15:13 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__element"></div>
вот эти элементы должны быть завернуты в общего родителя с фиксированной высотой и способом выравнивания этих самых элементов по нижней границе + также можно добавить gap

2024-03-06 18:21 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__element"></div>
Завернул, убрал высоту из свойств элемента.

2024-03-11 14:13 UTC, GSemikozov requested changes

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__element"></div>
в histogram__bottom надо завернуть только histogram__element, histogram__number - это отдельный элемент между bottom + top

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 24px;
не убрано (удалить max-height)

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    text-align: left;
лишнее

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 100%;
лишнее

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 115px;
лишнее

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 100%;
лишнее

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 39px 1px;
gap: 1px; margin-top: 39px

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 26px 32px;
`16 24 24`

2024-03-11 14:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-content: self-start;
лишнее

2024-03-12 12:14 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    min-width: 9px;
Сделал.

2024-03-12 12:15 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 24px;
Удалил max-height.

2024-03-12 12:16 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/index.html
> +                <a class="histogram__button">View all</a>
Переделал в элемент link.

2024-03-12 12:18 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__element"></div>
Принял. переделал.

2024-03-12 12:24 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    text-align: left;
Удалил.

2024-03-12 12:24 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 100%;
Удалил.

2024-03-12 12:25 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    gap: 39px 1px;
Переделал.

2024-03-12 12:27 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 26px 32px;
Паддинги изменил.

2024-03-12 12:27 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    align-content: self-start;
Удалил.

2024-03-12 12:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-14 10:42 UTC, GSemikozov requested changes

2024-03-14 10:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
надо удалить justify-content: space-between;

2024-03-14 10:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 100%;
flex-basis: 100%; все еще здесь

2024-03-14 10:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
height: 50px; надо удалить

2024-03-14 10:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
разную высоту колонкам можно задавать через модификаторы (высота - в процентах)

2024-03-14 19:33 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 100%;
Убрал.

2024-03-14 19:34 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
Удалил.

2024-03-14 19:35 UTC, ArtemViktorovitch commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
Понял. Попробую.

2024-03-14 20:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-15 15:11 UTC, GSemikozov approved these changes

2024-03-15 15:11 UTC, merged