solution for 05 lection tooltip
js-tasks-ru/htmlcss-20240216_del-ry4me pull request #9
Opened 2024-03-03 09:30 UTC by ArtemViktorovitch

2024-03-03 09:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-04 21:28 UTC, GSemikozov approved these changes

2024-03-04 21:28 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-03-04 21:28 UTC, GSemikozov requested changes
осталось исправить конфликты

2024-03-05 08:52 UTC, ArtemViktorovitch commented
Кажется разрешил конфликт

2024-03-06 15:16 UTC, GSemikozov approved these changes

2024-03-06 15:16 UTC, merged